import type { Staff, Job, Alert, Activity } from "@/lib/types"

const now = new Date()
const today = new Date(now.getFullYear(), now.getMonth(), now.getDate())
today.setHours(0, 0, 0, 0)

export const mockStaff: Staff[] = [
  {
    id: "1",
    name: "Aisha Al-Farsi",
    role: "Senior Cleaner",
    phone: "+966 50 123 4567",
    zone: "Al Olaya",
    status: "on-job",
    location: { lat: 24.7036, lng: 46.6753 },
    efficiency: 95,
    rating: 4.8,
    timeRemaining: 42,
    nextBookingTime: new Date(today.getTime() + 13 * 60 * 60 * 1000),
    bookings: [
      {
        id: "job-1",
        time: new Date(today.getTime() + 9 * 60 * 60 * 1000),
        endTime: new Date(today.getTime() + 11 * 60 * 60 * 1000),
        customerName: "Ahmed Al-Rashid",
        address: "123 King Fahd Rd, Al Olaya",
        serviceType: "Deep Clean",
        status: "in-progress",
      },
      {
        id: "job-2",
        time: new Date(today.getTime() + 13 * 60 * 60 * 1000),
        endTime: new Date(today.getTime() + 15 * 60 * 60 * 1000),
        customerName: "Fatima Hassan",
        address: "456 Tahlia St, Al Olaya",
        serviceType: "Standard Clean",
        status: "scheduled",
      },
    ],
  },
  {
    id: "2",
    name: "Omar Hassan",
    role: "Maintenance Tech",
    phone: "+966 50 234 5678",
    zone: "Al Malaz",
    status: "en-route",
    location: { lat: 24.6615, lng: 46.7288 },
    efficiency: 88,
    rating: 4.6,
    nextBookingTime: new Date(today.getTime() + 10.5 * 60 * 60 * 1000),
    bookings: [
      {
        id: "job-3",
        time: new Date(today.getTime() + 10.5 * 60 * 60 * 1000),
        endTime: new Date(today.getTime() + 12.5 * 60 * 60 * 1000),
        customerName: "Khalid Al-Mutairi",
        address: "789 Al Malaz District",
        serviceType: "Standard Clean",
        status: "scheduled",
      },
    ],
  },
  {
    id: "3",
    name: "Fatima Noor",
    role: "Senior Cleaner",
    phone: "+966 50 345 6789",
    zone: "Al Muruj",
    status: "available",
    location: { lat: 24.7523, lng: 46.6398 },
    efficiency: 92,
    rating: 4.9,
    nextBookingTime: new Date(today.getTime() + 14 * 60 * 60 * 1000),
    bookings: [
      {
        id: "job-4",
        time: new Date(today.getTime() + 14 * 60 * 60 * 1000),
        endTime: new Date(today.getTime() + 16 * 60 * 60 * 1000),
        customerName: "Sara Al-Dosari",
        address: "321 Al Muruj Compound",
        serviceType: "Sanitization",
        status: "scheduled",
      },
    ],
  },
  {
    id: "4",
    name: "Khalid Mansour",
    role: "Deep Clean Specialist",
    phone: "+966 50 456 7890",
    zone: "Diplomatic Quarter",
    status: "on-job",
    location: { lat: 24.6811, lng: 46.6205 },
    efficiency: 94,
    rating: 4.7,
    timeRemaining: 18,
    nextBookingTime: new Date(today.getTime() + 11 * 60 * 60 * 1000),
    bookings: [
      {
        id: "job-5",
        time: new Date(today.getTime() + 8 * 60 * 60 * 1000),
        endTime: new Date(today.getTime() + 10 * 60 * 60 * 1000),
        customerName: "Mohammed Al-Salem",
        address: "555 Diplomatic Quarter",
        serviceType: "Deep Clean",
        status: "in-progress",
      },
      {
        id: "job-6",
        time: new Date(today.getTime() + 11 * 60 * 60 * 1000),
        endTime: new Date(today.getTime() + 13 * 60 * 60 * 1000),
        customerName: "Noura Al-Faisal",
        address: "667 Al Safarat District",
        serviceType: "Standard Clean",
        status: "scheduled",
      },
    ],
  },
  {
    id: "5",
    name: "Sara Al-Zahrani",
    role: "Team Lead",
    phone: "+966 50 567 8901",
    zone: "Al Olaya",
    status: "available",
    location: { lat: 24.6956, lng: 46.685 },
    efficiency: 97,
    rating: 4.95,
    bookings: [],
  },
  {
    id: "6",
    name: "Ahmed Qureshi",
    role: "Sanitization Expert",
    phone: "+966 50 678 9012",
    zone: "Al Rawdah",
    status: "en-route",
    location: { lat: 24.7289, lng: 46.7098 },
    efficiency: 89,
    rating: 4.5,
    nextBookingTime: new Date(today.getTime() + 12 * 60 * 60 * 1000),
    bookings: [
      {
        id: "job-7",
        time: new Date(today.getTime() + 12 * 60 * 60 * 1000),
        endTime: new Date(today.getTime() + 14 * 60 * 60 * 1000),
        customerName: "Dr. Yusuf Al-Qahtani",
        address: "890 Al Rawdah District",
        serviceType: "Sanitization",
        status: "scheduled",
      },
    ],
  },
  {
    id: "7",
    name: "Layla Ibrahim",
    role: "Senior Cleaner",
    phone: "+966 50 789 0123",
    zone: "Al Olaya",
    status: "available",
    location: { lat: 24.7136, lng: 46.6653 },
    efficiency: 91,
    rating: 4.7,
    nextBookingTime: new Date(today.getTime() + 14 * 60 * 60 * 1000),
    bookings: [
      {
        id: "job-10",
        time: new Date(today.getTime() + 14 * 60 * 60 * 1000),
        endTime: new Date(today.getTime() + 16 * 60 * 60 * 1000),
        customerName: "Huda Al-Otaibi",
        address: "Al Faisaliah Tower, Al Olaya",
        serviceType: "Standard Clean",
        status: "scheduled",
      },
    ],
  },
  {
    id: "8",
    name: "Yousef Al-Qahtani",
    role: "Maintenance Tech",
    phone: "+966 50 890 1234",
    zone: "Al Malaz",
    status: "available",
    location: { lat: 24.6715, lng: 46.7188 },
    efficiency: 87,
    rating: 4.4,
    nextBookingTime: new Date(today.getTime() + 13 * 60 * 60 * 1000),
    bookings: [
      {
        id: "job-11",
        time: new Date(today.getTime() + 13 * 60 * 60 * 1000),
        endTime: new Date(today.getTime() + 15 * 60 * 60 * 1000),
        customerName: "Reem Al-Harbi",
        address: "Tahlia St, Al Malaz",
        serviceType: "Standard Clean",
        status: "scheduled",
      },
    ],
  },
  {
    id: "9",
    name: "Hana Al-Otaibi",
    role: "Deep Clean Specialist",
    phone: "+966 50 901 2345",
    zone: "Diplomatic Quarter",
    status: "on-job",
    location: { lat: 24.6711, lng: 46.6305 },
    efficiency: 93,
    rating: 4.8,
    timeRemaining: 35,
    nextBookingTime: new Date(today.getTime() + 14.5 * 60 * 60 * 1000),
    bookings: [
      {
        id: "job-12",
        time: new Date(today.getTime() + 10 * 60 * 60 * 1000),
        endTime: new Date(today.getTime() + 12 * 60 * 60 * 1000),
        customerName: "Jean-Pierre Dubois",
        address: "Diplomatic Quarter",
        serviceType: "Sanitization",
        status: "scheduled",
      },
      {
        id: "job-13",
        time: new Date(today.getTime() + 14.5 * 60 * 60 * 1000),
        endTime: new Date(today.getTime() + 16.5 * 60 * 60 * 1000),
        customerName: "James Wilson",
        address: "Diplomatic Quarter",
        serviceType: "Deep Clean",
        status: "scheduled",
      },
    ],
  },
  {
    id: "10",
    name: "Nadia Hussein",
    role: "Senior Cleaner",
    phone: "+966 50 012 3456",
    zone: "Al Muruj",
    status: "on-job",
    location: { lat: 24.7423, lng: 46.6298 },
    efficiency: 90,
    rating: 4.6,
    timeRemaining: 55,
    nextBookingTime: new Date(today.getTime() + 12 * 60 * 60 * 1000),
    bookings: [
      {
        id: "job-14",
        time: new Date(today.getTime() + 8.5 * 60 * 60 * 1000),
        endTime: new Date(today.getTime() + 10.5 * 60 * 60 * 1000),
        customerName: "Abdullah Al-Shammari",
        address: "Prince Sultan Rd, Al Muruj",
        serviceType: "Standard Clean",
        status: "in-progress",
      },
    ],
  },
  {
    id: "11",
    name: "Rashid Al-Dosari",
    role: "Sanitization Expert",
    phone: "+966 50 123 4568",
    zone: "Al Rawdah",
    status: "available",
    location: { lat: 24.7189, lng: 46.6998 },
    efficiency: 86,
    rating: 4.3,
    nextBookingTime: new Date(today.getTime() + 15 * 60 * 60 * 1000),
    bookings: [
      {
        id: "job-15",
        time: new Date(today.getTime() + 15 * 60 * 60 * 1000),
        endTime: new Date(today.getTime() + 17 * 60 * 60 * 1000),
        customerName: "Dr. Laila Al-Naimi",
        address: "Al Rawdah District",
        serviceType: "Sanitization",
        status: "scheduled",
      },
    ],
  },
  {
    id: "12",
    name: "Mona Saleh",
    role: "Team Lead",
    phone: "+966 50 234 5679",
    zone: "Al Malaz",
    status: "offline",
    location: { lat: 24.6515, lng: 46.7388 },
    efficiency: 96,
    rating: 4.9,
    bookings: [],
  },
  {
    id: "13",
    name: "Tariq Al-Harbi",
    role: "Deep Clean Specialist",
    phone: "+966 50 345 6780",
    zone: "Al Malaz",
    status: "on-job",
    location: { lat: 24.6615, lng: 46.7188 },
    efficiency: 88,
    rating: 4.5,
    timeRemaining: 90,
    nextBookingTime: new Date(today.getTime() + 13 * 60 * 60 * 1000),
    bookings: [
      {
        id: "job-16",
        time: new Date(today.getTime() + 9 * 60 * 60 * 1000),
        endTime: new Date(today.getTime() + 12 * 60 * 60 * 1000),
        customerName: "Faisal Al-Ghamdi",
        address: "King Abdulaziz Rd, Al Malaz",
        serviceType: "Deep Clean",
        status: "in-progress",
      },
      {
        id: "job-17",
        time: new Date(today.getTime() + 13 * 60 * 60 * 1000),
        endTime: new Date(today.getTime() + 14.5 * 60 * 60 * 1000),
        customerName: "Majid Al-Subaie",
        address: "Al Malaz District",
        serviceType: "Standard Clean",
        status: "scheduled",
      },
    ],
  },
  {
    id: "14",
    name: "Zainab Al-Amri",
    role: "Senior Cleaner",
    phone: "+966 50 456 7891",
    zone: "Al Muruj",
    status: "available",
    location: { lat: 24.7523, lng: 46.6498 },
    efficiency: 91,
    rating: 4.7,
    nextBookingTime: new Date(today.getTime() + 11 * 60 * 60 * 1000),
    bookings: [
      {
        id: "job-18",
        time: new Date(today.getTime() + 11 * 60 * 60 * 1000),
        endTime: new Date(today.getTime() + 13 * 60 * 60 * 1000),
        customerName: "Maryam Al-Tamimi",
        address: "Al Muruj Compound",
        serviceType: "Standard Clean",
        status: "scheduled",
      },
    ],
  },
]

export const mockJobs: Job[] = [
  {
    id: "job-1",
    staffId: "1",
    customerName: "Ahmed Al-Rashid",
    address: "123 King Fahd Rd, Al Olaya",
    serviceType: "Deep Clean",
    scheduledTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 11 * 60 * 60 * 1000),
    status: "in-progress",
    location: { lat: 24.6982, lng: 46.6856 },
    startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-2",
    staffId: "1",
    customerName: "Fatima Hassan",
    address: "456 Tahlia St, Al Olaya",
    serviceType: "Standard Clean",
    scheduledTime: new Date(today.getTime() + 13 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 15 * 60 * 60 * 1000),
    status: "scheduled",
    location: { lat: 24.692, lng: 46.69 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-3",
    staffId: "2",
    customerName: "Khalid Al-Mutairi",
    address: "789 Al Malaz District",
    serviceType: "Standard Clean",
    scheduledTime: new Date(today.getTime() + 10.5 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 12.5 * 60 * 60 * 1000),
    status: "scheduled",
    location: { lat: 24.67, lng: 46.73 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-4",
    staffId: "3",
    customerName: "Sara Al-Dosari",
    address: "321 Al Muruj Compound",
    serviceType: "Sanitization",
    scheduledTime: new Date(today.getTime() + 14 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 16 * 60 * 60 * 1000),
    status: "scheduled",
    location: { lat: 24.76, lng: 46.64 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-5",
    staffId: "4",
    customerName: "Mohammed Al-Salem",
    address: "555 Diplomatic Quarter",
    serviceType: "Deep Clean",
    scheduledTime: new Date(today.getTime() + 8 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 10 * 60 * 60 * 1000),
    status: "in-progress",
    location: { lat: 24.6833, lng: 46.6167 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-6",
    staffId: "4",
    customerName: "Noura Al-Faisal",
    address: "667 Al Safarat District",
    serviceType: "Standard Clean",
    scheduledTime: new Date(today.getTime() + 11 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 13 * 60 * 60 * 1000),
    status: "scheduled",
    location: { lat: 24.688, lng: 46.62 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-7",
    staffId: "6",
    customerName: "Dr. Yusuf Al-Qahtani",
    address: "890 Al Rawdah District",
    serviceType: "Sanitization",
    scheduledTime: new Date(today.getTime() + 12 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 14 * 60 * 60 * 1000),
    status: "at-risk",
    location: { lat: 24.732, lng: 46.71 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-8",
    staffId: "",
    customerName: "Hassan Al-Mahmoud",
    address: "100 Prince Mohammed Rd, Al Olaya",
    serviceType: "Deep Clean",
    scheduledTime: new Date(today.getTime() + 11 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 13 * 60 * 60 * 1000),
    status: "at-risk",
    location: { lat: 24.71, lng: 46.675 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-0",
    staffId: "1",
    customerName: "Salma Al-Khaldi",
    address: "10 Prince Turki Rd, Al Olaya",
    serviceType: "Standard Clean",
    scheduledTime: new Date(today.getTime() + 7 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 8.5 * 60 * 60 * 1000),
    status: "completed",
    location: { lat: 24.7, lng: 46.68 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-10",
    staffId: "7",
    customerName: "Huda Al-Otaibi",
    address: "Al Faisaliah Tower, Al Olaya",
    serviceType: "Standard Clean",
    scheduledTime: new Date(today.getTime() + 14 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 16 * 60 * 60 * 1000),
    status: "scheduled",
    location: { lat: 24.76, lng: 46.64 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-11",
    staffId: "8",
    customerName: "Reem Al-Harbi",
    address: "Tahlia St, Al Malaz",
    serviceType: "Standard Clean",
    scheduledTime: new Date(today.getTime() + 13 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 15 * 60 * 60 * 1000),
    status: "scheduled",
    location: { lat: 24.672, lng: 46.715 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-12",
    staffId: "9",
    customerName: "Jean-Pierre Dubois",
    address: "Diplomatic Quarter",
    serviceType: "Sanitization",
    scheduledTime: new Date(today.getTime() + 10 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 12 * 60 * 60 * 1000),
    status: "scheduled",
    location: { lat: 24.678, lng: 46.625 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-13",
    staffId: "9",
    customerName: "James Wilson",
    address: "Diplomatic Quarter",
    serviceType: "Deep Clean",
    scheduledTime: new Date(today.getTime() + 14.5 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 16.5 * 60 * 60 * 1000),
    status: "scheduled",
    location: { lat: 24.665, lng: 46.73 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-14",
    staffId: "10",
    customerName: "Abdullah Al-Shammari",
    address: "Prince Sultan Rd, Al Muruj",
    serviceType: "Standard Clean",
    scheduledTime: new Date(today.getTime() + 8.5 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 10.5 * 60 * 60 * 1000),
    status: "in-progress",
    location: { lat: 24.752, lng: 46.638 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-15",
    staffId: "11",
    customerName: "Dr. Laila Al-Naimi",
    address: "Al Rawdah District",
    serviceType: "Sanitization",
    scheduledTime: new Date(today.getTime() + 15 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 17 * 60 * 60 * 1000),
    status: "scheduled",
    location: { lat: 24.728, lng: 46.705 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-16",
    staffId: "13",
    customerName: "Faisal Al-Ghamdi",
    address: "King Abdulaziz Rd, Al Malaz",
    serviceType: "Deep Clean",
    scheduledTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 12 * 60 * 60 * 1000),
    status: "in-progress",
    location: { lat: 24.665, lng: 46.73 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-17",
    staffId: "13",
    customerName: "Majid Al-Subaie",
    address: "Al Malaz District",
    serviceType: "Standard Clean",
    scheduledTime: new Date(today.getTime() + 13 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 14.5 * 60 * 60 * 1000),
    status: "scheduled",
    location: { lat: 24.76, lng: 46.65 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-18",
    staffId: "14",
    customerName: "Maryam Al-Tamimi",
    address: "Al Muruj Compound",
    serviceType: "Standard Clean",
    scheduledTime: new Date(today.getTime() + 11 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 13 * 60 * 60 * 1000),
    status: "scheduled",
    location: { lat: 24.7574, lng: 46.6428 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-cancelled-1",
    staffId: "",
    customerName: "Nasser Al-Dossary",
    address: "Al Faisaliah Tower, Al Olaya",
    serviceType: "Standard Clean",
    scheduledTime: new Date(today.getTime() + 14 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 16 * 60 * 60 * 1000),
    status: "cancelled",
    location: { lat: 24.76, lng: 46.64 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-cancelled-2",
    staffId: "",
    customerName: "Lina Al-Turki",
    address: "Olaya Towers, Al Olaya",
    serviceType: "Deep Clean",
    scheduledTime: new Date(today.getTime() + 12 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 14 * 60 * 60 * 1000),
    status: "cancelled",
    location: { lat: 24.71, lng: 46.675 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-completed-1",
    staffId: "8",
    customerName: "Reem Al-Harbi",
    address: "Tahlia St, Al Malaz",
    serviceType: "Standard Clean",
    scheduledTime: new Date(today.getTime() + 8 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 10 * 60 * 60 * 1000),
    status: "completed",
    location: { lat: 24.672, lng: 46.715 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-completed-2",
    staffId: "5",
    customerName: "Omar Al-Zahrani",
    address: "Al Olaya District",
    serviceType: "Deep Clean",
    scheduledTime: new Date(today.getTime() + 7 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    status: "completed",
    location: { lat: 24.6956, lng: 46.685 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
  {
    id: "job-completed-3",
    staffId: "3",
    customerName: "Amal Al-Rashidi",
    address: "Al Muruj Compound",
    serviceType: "Sanitization",
    scheduledTime: new Date(today.getTime() + 6 * 60 * 60 * 1000),
    endTime: new Date(today.getTime() + 8 * 60 * 60 * 1000),
    status: "completed",
    location: { lat: 24.7523, lng: 46.6398 },
     startTime: new Date(today.getTime() + 9 * 60 * 60 * 1000),
    type: "deep-clean",
  },
]

export const mockAlerts: Alert[] = [
  {
    id: "alert-1",
    type: "staff-offline",
    severity: "high",
    title: "Staff offline during scheduled hours",
    description: "James Wilson is offline but has a booking at 12:00 PM",
    staffId: "6",
    jobId: "job-7",
    timestamp: new Date(now.getTime() - 42000),
    dismissed: false,
  },
  {
    id: "alert-2",
    type: "unassigned",
    severity: "high",
    title: "Unassigned booking nearing start",
    description: "City Gym booking at 11:00 AM has no assigned staff",
    jobId: "job-8",
    timestamp: new Date(now.getTime() - 15000),
    dismissed: false,
  },
  {
    id: "alert-3",
    type: "running-long",
    severity: "medium",
    title: "Job running longer than expected",
    description: "David Kim's job at Embassy Services may overrun",
    staffId: "4",
    jobId: "job-5",
    timestamp: new Date(now.getTime() - 120000),
    dismissed: false,
  },
  {
    id: "alert-4",
    type: "late-arrival",
    severity: "low",
    title: "Late arrival warning",
    description: "Marcus Johnson may arrive 5 mins late to Stellar Office",
    staffId: "2",
    jobId: "job-3",
    timestamp: new Date(now.getTime() - 18000),
    dismissed: false,
  },
  {
    id: "alert-5",
    type: "staff-offline",
    severity: "high",
    title: "Staff offline during scheduled hours",
    description: "Carlos Mendez is offline but has no bookings",
    staffId: "12",
    timestamp: new Date(now.getTime() - 3600000),
    dismissed: false,
  },
]

export const mockActivities: Activity[] = [
  {
    id: "act-risk-1",
    type: "job-at-risk",
    actor: "System",
    actorType: "system",
    action: "flagged job at Kingdom Tower as at-risk - staff running 15min behind",
    relatedStaffId: "7",
    relatedJobId: "job-9",
    timestamp: new Date(now.getTime() - 42000), // 42 seconds ago
  },
  {
    id: "act-cancelled-1",
    type: "booking-cancelled",
    actor: "Admin",
    actorType: "system",
    action: "cancelled booking at Al Faisaliah Tower - customer request",
    relatedStaffId: "8",
    relatedJobId: "job-cancelled-1",
    timestamp: new Date(now.getTime() - 15000), // 15 seconds ago
  },
  {
    id: "act-new-1",
    type: "status-change",
    actor: "Priya Sharma",
    actorType: "staff",
    action: "went available after break",
    relatedStaffId: "11",
    timestamp: new Date(now.getTime() - 8000), // 8 seconds ago
  },
  {
    id: "act-completed-1",
    type: "booking-completed",
    actor: "Ahmed Al-Rashid",
    actorType: "staff",
    action: "completed job at Riyadh Gallery Mall - 10min early",
    relatedStaffId: "8",
    relatedJobId: "job-completed-1",
    timestamp: new Date(now.getTime() - 12000), // 12 seconds ago
  },
  {
    id: "act-risk-2",
    type: "job-at-risk",
    actor: "System",
    actorType: "system",
    action: "flagged Panorama Mall job as at-risk - traffic delay detected",
    relatedStaffId: "10",
    relatedJobId: "job-14",
    timestamp: new Date(now.getTime() - 35000), // 35 seconds ago
  },
  {
    id: "act-new-2",
    type: "booking-assigned",
    actor: "System",
    actorType: "system",
    action: "auto-assigned Yuki Tanaka to Hayat Mall",
    relatedStaffId: "14",
    relatedJobId: "job-18",
    timestamp: new Date(now.getTime() - 18000), // 18 seconds ago
  },
  {
    id: "act-cancelled-2",
    type: "booking-cancelled",
    actor: "System",
    actorType: "system",
    action: "auto-cancelled unassigned job at Olaya Towers - no staff available",
    relatedJobId: "job-cancelled-2",
    timestamp: new Date(now.getTime() - 10000), // 10 seconds ago
  },
  {
    id: "act-completed-2",
    type: "booking-completed",
    actor: "Maria Santos",
    actorType: "staff",
    action: "completed deep cleaning at French Embassy",
    relatedStaffId: "9",
    relatedJobId: "job-12",
    timestamp: new Date(now.getTime() - 20000), // 20 seconds ago
  },
  {
    id: "act-new-3",
    type: "booking-completed",
    actor: "Noor Abdullah",
    actorType: "staff",
    action: "completed early at Al Malaz Sports Club",
    relatedStaffId: "13",
    relatedJobId: "job-16",
    timestamp: new Date(now.getTime() - 45000), // 45 seconds ago
  },
  {
    id: "act-1",
    type: "status-change",
    actor: "Sarah Chen",
    actorType: "staff",
    action: "started job at Acme Corp",
    relatedStaffId: "1",
    relatedJobId: "job-1",
    timestamp: new Date(now.getTime() - 60000),
  },
  {
    id: "act-2",
    type: "booking-completed",
    actor: "Sarah Chen",
    actorType: "staff",
    action: "completed job at Morning Cafe",
    relatedStaffId: "1",
    relatedJobId: "job-0",
    timestamp: new Date(now.getTime() - 3600000),
  },
  {
    id: "act-3",
    type: "booking-assigned",
    actor: "System",
    actorType: "system",
    action: "assigned David Kim to Embassy Services",
    relatedStaffId: "4",
    relatedJobId: "job-5",
    timestamp: new Date(now.getTime() - 7200000),
  },
  {
    id: "act-4",
    type: "status-change",
    actor: "Marcus Johnson",
    actorType: "staff",
    action: "went en-route to Stellar Office",
    relatedStaffId: "2",
    relatedJobId: "job-3",
    timestamp: new Date(now.getTime() - 15000),
  },
  {
    id: "act-5",
    type: "booking-reassigned",
    actor: "Admin",
    actorType: "system",
    action: "reassigned Wellness Center from Team Pool to Emily Rodriguez",
    relatedStaffId: "3",
    relatedJobId: "job-4",
    timestamp: new Date(now.getTime() - 10800000),
  },
  {
    id: "act-6",
    type: "status-change",
    actor: "Fatima Al-Hassan",
    actorType: "staff",
    action: "started job at Kingdom Tower Office",
    relatedStaffId: "7",
    relatedJobId: "job-9",
    timestamp: new Date(now.getTime() - 30000),
  },
  {
    id: "act-7",
    type: "status-change",
    actor: "Ahmed Al-Rashid",
    actorType: "staff",
    action: "went available for new bookings",
    relatedStaffId: "8",
    timestamp: new Date(now.getTime() - 12000),
  },
  {
    id: "act-8",
    type: "booking-assigned",
    actor: "System",
    actorType: "system",
    action: "assigned Maria Santos to French Embassy",
    relatedStaffId: "9",
    relatedJobId: "job-12",
    timestamp: new Date(now.getTime() - 20000),
  },
  {
    id: "act-9",
    type: "status-change",
    actor: "Omar Khalil",
    actorType: "staff",
    action: "started job at Panorama Mall",
    relatedStaffId: "10",
    relatedJobId: "job-14",
    timestamp: new Date(now.getTime() - 55000),
  },
  {
    id: "act-10",
    type: "status-change",
    actor: "Priya Sharma",
    actorType: "staff",
    action: "went available for new bookings",
    relatedStaffId: "11",
    timestamp: new Date(now.getTime() - 3000),
  },
  {
    id: "act-11",
    type: "status-change",
    actor: "Carlos Mendez",
    actorType: "staff",
    action: "went offline",
    relatedStaffId: "12",
    timestamp: new Date(now.getTime() - 3600000),
  },
  {
    id: "act-12",
    type: "status-change",
    actor: "Noor Abdullah",
    actorType: "staff",
    action: "started job at Al Malaz Sports Club",
    relatedStaffId: "13",
    relatedJobId: "job-16",
    timestamp: new Date(now.getTime() - 45000),
  },
  {
    id: "act-13",
    type: "status-change",
    actor: "Yuki Tanaka",
    actorType: "staff",
    action: "went en-route to Hayat Mall",
    relatedStaffId: "14",
    relatedJobId: "job-18",
    timestamp: new Date(now.getTime() - 18000),
  },
]
